apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gethomepage
  name: traefik-crd-access
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: gethomepage
  name: traefik-crd-access-binding
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: gethomepage
roleRef:
  kind: Role
  name: traefik-crd-access
  apiGroup: rbac.authorization.k8s.io