apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:brooklyn-ch/gh_kubernetes-dev.git
    targetRevision: HEAD
    path: apps/gethomepage
  destination: 
    server: https://kubernetes.default.svc
    namespace: gethomepage

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true