---
#DONE DIRECTLY VIA HELM CHART
#apiVersion: traefik.io/v1alpha1
#kind: IngressRoute
#metadata:
#  name: rancher-ingressroute
#  namespace: cattle-system
#  annotations:
#    gethomepage.dev/href: "https://rancher.denniscloud.io"
#    gethomepage.dev/enabled: "true"
#    gethomepage.dev/description: Kubernetes Manager
#    gethomepage.dev/group: Services
#    gethomepage.dev/icon: rancher.png
#    gethomepage.dev/app: rancher
#    gethomepage.dev/name: rancher
#    gethomepage.dev/widget.type: "rancher"
#    gethomepage.dev/widget.url: "rancher"
#    gethomepage.dev/pod-selector: ""
#spec:
#  entryPoints:
#    - websecure
#  routes:
#    - match: Host(`rancher.denniscloud.io`)
#      kind: Rule
#      services:
#        - name: rancher
#          port: 80
#  tls:
#    secretName: rancher-cert-secret