apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
  namespace: gethomepage
  labels:
    app: homepage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      frontend: "block" # Matches the frontend type in Longhorn
    volumeHandle: homepage-pv # Use the same volume name as in Longhorn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: longhorn.io/node-tag # Key used to define Longhorn node tags
              operator: In
              values:
                - storage # The value of the tag you specified in Longhorn