apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secrets
  namespace: vikunja
type: Opaque
data:
  POSTGRES_DB: dmlrdW5qYV9kYg==
  POSTGRES_USER: dmlrdW5qYS1hZG1pbg==
  POSTGRES_PASSWORD: RGVubmlzVmlrdW5qYURC
  VIKUNJA_SECRET_KEY: T0dsaUVKRkZDWm5QTEtZRWR3aE91ZHNzbTNBOExvWmJhWHNPSHlGVlJINEhjb3loVjN5ME5XeWh0RVAxNTRUblNvYk05WjV2T2UzNE8=
  VIKUNJA_MAIL: dGFza3NAZGVubmlzY2xvdWQuaW8=
  VIKUNJA_MAIL_PW: V05MREdYUlVaNzc5NjFESw==