apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
  labels:
    app: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
      - name: vikunja
        image: vikunja/vikunja:latest
        ports:
        - containerPort: 3456
        env:
        - name: VIKUNJA_CONFIG
          value: /etc/vikunja/config.yml
        - name: VIKUNJA_DATABASE_HOST
          value: "192.168.100.47"
        - name: VIKUNJA_DATABASE_TYPE
          value: "postgres"
        - name: VIKUNJA_DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: POSTGRES_DB
        - name: VIKUNJA_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: POSTGRES_USER
        - name: VIKUNJA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: POSTGRES_PASSWORD
        - name: VIKUNJA_SERVICE_JWTSECRET
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: VIKUNJA_SECRET_KEY
        - name: VIKUNJA_MAILER_ENABLED
          value: "true"
        - name: VIKUNJA_MAILER_HOST
          value: "smtp.protonmail.ch"
        - name: VIKUNJA_MAILER_PORT
          value: "587"
        - name: VIKUNJA_MAILER_AUTHTYPE
          value: "plain"
        - name: VIKUNJA_MAILER_USERNAME
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: VIKUNJA_MAIL
        - name: VIKUNJA_MAILER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: VIKUNJA_MAIL_PW
        - name: VIKUNJA_MAILER_FROMEMAIL
          valueFrom:
            secretKeyRef:
              name: vikunja-secrets
              key: VIKUNJA_MAIL
        volumeMounts:
        - mountPath: /app/vikunja/files
          name: files-storage
        - mountPath: /etc/vikunja/config.yml
          name: vikunja-config-volume
          subPath: config.yml
      volumes:
      - name: vikunja-config-volume
        configMap:
          name: vikunja-config
      - name: files-storage
        persistentVolumeClaim:
          claimName: vikunja-files