---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wikijs-certificate
  namespace: wikijs
spec:
   secretName: wikijs-cert-secret
   issuerRef:
     name: cloudflare-clusterissuer
     kind: ClusterIssuer
   dnsNames:
     - wiki.denniscloud.io