apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 2Gi
  storageClassName: longhorn