apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-storage
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 20Gi
  storageClassName: longhorn