---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: outline-certificate
  namespace: outline
spec:
   secretName: outline-cert-secret
   issuerRef:
     name: cloudflare-clusterissuer
     kind: ClusterIssuer
   dnsNames:
     - notes.denniscloud.io