apiVersion: v1
kind: ConfigMap
metadata:
  name: outline-config
  namespace: outline
data:
  NODE_ENV: "production"
  PGSSLMODE: "disable"
  COLLABORATION_URL: ""
  FILE_STORAGE: "local"
  OIDC_AUTH_URI: "https://authentik.denniscloud.io/application/o/authorize/"
  OIDC_TOKEN_URI: "https://authentik.denniscloud.io/application/o/token/"
  OIDC_USERINFO_URI: "https://authentik.denniscloud.io/application/o/userinfo/"
  OIDC_LOGOUT_URI: "https://authentik.denniscloud.io/application/o/outline/end-session/"
  OIDC_USERNAME_CLAIM: "preferred_username"
  OIDC_DISPLAY_NAME: "DennisCloud-Authentik"
  OIDC_SCOPES: "openid profile email"
  SMTP_HOST: "smtp.protonmail.ch"
  SMTP_PORT: "587"
  SMTP_FROM_EMAIL: "notes@denniscloud.io"
  SMTP_REPLY_EMAIL: "notes@denniscloud.io"
  SMTP_TLS_CIPHERS: ""
  SMTP_SECURE: "true"
  DEFAULT_LANGUAGE: "en_US"
  RATE_LIMITER_ENABLED: "true"
  RATE_LIMITER_REQUESTS: "1000"
  RATE_LIMITER_DURATION_WINDOW: "60"