---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drawio-certificate
  namespace: drawio
spec:
   secretName: drawio-cert-secret
   issuerRef:
     name: cloudflare-clusterissuer
     kind: ClusterIssuer
   dnsNames:
     - drawio.denniscloud.io