apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drawio-data
  namespace: drawio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static