---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-certificate
  namespace: cattle-system
spec:
   secretName: rancher-cert-secret
   issuerRef:
     name: cloudflare-clusterissuer
     kind: ClusterIssuer
   dnsNames:
     - rancher.denniscloud.io